### ISSUE TITLE
Electrumx backend: Address transactions sometimes not sorted in expected order

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#424]
Looking up address `3BJ7yNNYcUzT9BWC7STxc6YPWS7CKNUFYH` the 2 transactions was confirmed in the same block and therefore has the same date, but the spending from the address should be ordered on top of the deposit transaction.

**Comment by wiz** [comment]
@knorrium does this still reproduce after merging #814 ?

**Comment by softsimon** [comment]
I can simply reproduce this bug by simply opening the address on a romanz/electrs mempool instance.

<img width="1196" alt="Screen Shot 2021-11-27 at 16 45 08" src="https://user-images.githubusercontent.com/8561090/143681824-2cca845f-62a8-4de5-83ce-792ddf2a4e16.png">

**Comment by junderw** [comment]
Is this fixed now?

**Comment by softsimon** [comment]
> Is this fixed now?

I would guess no

**Comment by junderw** [comment]
Is there a public instance somewhere that uses romanz/electrs?

**Comment by wiz** [comment]
Yeah I think @thebluematt runs one at mempool.bitcoin.ninja

**Comment by antonilol** [comment]
on my local hosted mempool running on v2.5.0-dev [ab985afe] i still see this issue

**Comment by antonilol** [comment]
got this issue twice on mempool.space by broadcasting a tx and then spending it with another tx that was directly included in a block, not in the mempool (i had to because they did not adhere to policy rules)
https://mempool.space/testnet/address/tb1q00zgsyg58458544qnra8z47hs28w8sufmpy2xt

**Comment by junderw** [comment]
Found the root of the issue.

1. romanz stores the history entries in height from lowest to highest, then within the same block it stores position in block from lowest to highest)
2. esplora explicitly sorts the history entries for height from lowest to highest, but does not explicitly sort for block position, so the sort order is dependent on the order the rows come back from the DB. (there is a key based sort before the write operation, and for items with the same height and scripthash, the first difference is the F and S in the key (for funding and spending respectively))

esplora is in the wrong here, so if anything, the fact that we are wrong with romanz and "right" with esplora means that mempool is likely wrong.

The fix should be 2 fold:

1. Fix esplora to explicitly sort by block position (changing the DB key would be more performant, but requires reindex, we could bodge an impl that checks the block position every time we fetch them from DB by checking the block index.)
2. Once esplora matches romanz we need to fix mempool.

Alternatively, we could leave esplora as is and just sort the entries on the mempool side.

Thoughts?

**Comment by junderw** [comment]
For 2 ("fix mempool") this would be trivial. We should flip the sort order currently (by flipping the sides of - in the sort callback) then do `transactions.reverse()` afterward.

Currently the sort callback in mempool is bugged for transactions that are equal in block height.

We could also implement topological sort in JS and use it for the subarrays that have the same block height.

If we did that, it wouldn't matter what the ordering from Electrs/etc was.

Perhaps topological sort in mempool should be the solution to begin with... modifying the index in esplora seems like a pain to have to reindex everything.

**Comment by junderw** [comment]
*sigh* I hate topological sort.
